### PR TITLE
Forms

### PR DESCRIPTION
**Pull request by fredrikNordvallForsberg**
Adds support for form elements by using code blocks of the form

    `<fieldname>`{.input <attributes>}

or for a textarea (unless <attributes> contain a type)

    ```{.input <attributes>}
    <fieldname>
    ```
A submit button is created by

    `<label>`{.input type=submit <other-attributes>}

Form elements are populated with their corresponding POST data, if it exists (ie filling in a form and pressing submit will keep all submitted data in the fields).

Shonkier programs can get access to the POST data with name <fieldname> by

    'field(<fieldname>)

GET parameters by

    'param(<parametername>)

and Pandoc meta values in general by

    `meta(<value>)

Things to consider:
* Are we happy with `'field`, `'param` and `'meta`?
* There's possible extensions such as default values and attaching a shonkier term to act as a parser for the field -- the former is easy to achieve, because it happens locally (if we wanted it, how about giving a shonkier term that gets the current value or `Nil` as an argument and computes how to populate the field value?), but the former is a bit annoying as we have to walk the document to extract these parsers. Since this can be achieved by

```
field'(p, f) -> p('field(f))
```

unless I'm missing something, I propose to keep it simple.
* Again the javascript backend is lagging behind: it doesn't know about `field` and `param` requests. For fields, I'm thinking to get the value straight from the DOM? Although we would have to think about how to make this play nice with Node.js, which doesn't have a DOM.

### CODE REVIEW

**Comment by pigworker** [comment]
As long as this doesn't break anything, I'm in favour of getting this operational, sooner rather than later. Many of the bikeshedding issues would benefit from experience.

Looks like a great start!

**Comment by fredrikNordvallForsberg** [comment]
> As long as this doesn't break anything, 

The build and tests work for me locally, but I'm not sure what is going on on github... Hoping @gallais will swoop in and fix things.

**Comment by gallais** [comment]
It builds! This is a very exciting step towards interactive pages. :fireworks:

**Comment by fredrikNordvallForsberg** [comment]
It still builds! :tada: Should I merge it?

**Comment by gallais** [comment]
>  Should I merge it?

Do we have `primStringToNum` and `primLitToString` in the haskell interpreter?

Edit: answering my own question: we do have `primStringToNum` which is added
by this PR but we do not have `primLitToString` AFAICT.

**Comment by pigworker** [comment]
Trying to be a reformed citizen, should we have a specific test file for prims (which should work for both runtimes), with an ad hoc coverage check that ensures every prim has at least one test?

**Comment by fredrikNordvallForsberg** [comment]
> Do we have `primStringToNum` and `primLitToString` in the haskell interpreter?

Yes, I added `primStringToNum` in this PR, and the *actual* name for `primLitToString` is `primNumToString` which was already there -- I only noticed that after fixing the JS implementation, `primNumToString` will actually work for arbitrary literals, so I renamed the function doing the work. However the name of the primitive remains the same.

**Comment by fredrikNordvallForsberg** [comment]
> should we have a specific test file for prims (which should work for both runtimes), with an ad hoc coverage check that ensures every prim has at least one test?

This is a good idea, and probably a matter of extending the existing [examples/primitives.shonkier](https://github.com/msp-strath/Mary/blob/forms/examples/primitives.shonkier) to have that coverage? (I just made sure it covers conversions from Num to String and back in the last commit.)

**Comment by gallais** [comment]
In the *Haskell* interpreter `primNumToString` will only work on nums AFAICT.
Not on arbitrary lits (we now have booleans too).

**Comment by fredrikNordvallForsberg** [comment]
Yes indeed, that's why I didn't rename the actual primitive, just the underlying JS implementation. Sorry if this was confusing.

**Comment by gallais** [comment]
Ah, I see that the code dispatching to that function has not changed! My bad.
But that means that we do have a different behaviour between the two
interpreters: in one case you'll get a "wrong type" error if you call the
primitive with a boolean while in the other you'll get the string representation.

But maybe this is not that important: I am in favour of replacing this primitive
with `primShow` anyway so that users may print any value they get their hands on.

**Comment by fredrikNordvallForsberg** [comment]
I just realised the same... I could make the behaviour consistent for now.

**Comment by pigworker** [comment]
I suspect that

    "`x`"

doesn't currently do what we want when `x` is a number or a boolean.

**Comment by gallais** [comment]
:rocket: it!

**Pull request merged**
